#!/usr/bin/env python3
"""Generate the offline catalog and portable downloads from canonical skill files."""
import json
import re
from pathlib import Path
from toolkit import ROOT, skills, sections, prompt_blocks, portable_files, archive_bytes, digest, public_files, read_public_file

LABELS = {
    'start-here': ('Find my first task', 'Start here', 'start', 'One useful draft and a clear next step.'),
    'announcement-writer': ('Draft a class update', 'Announcement writer', 'create', 'A draft in your voice, ready to review.'),
    'canvas-page-generator': ('Make a course page', 'Course page generator', 'create', 'Readable HTML for your course content.'),
    'quiz-builder': ('Build a question bank', 'Quiz builder', 'create', 'Questions, answer rationales, and an authoring table.'),
    'grading-assistant': ('Review rubric-based scores', 'Grading assistant', 'review', 'Proposed scores with evidence and review flags.'),
    'participation-scoring': ('Review participation', 'Participation scoring', 'review', 'An activity table checked against your rubric.'),
    'ai-output-checker': ('Check claims and numbers', 'AI output checker', 'review', 'Verified claims, calculations, and unresolved sources.'),
    'exam-rebalance': ('Check an exam', 'Exam rebalance', 'review', 'A coverage map and questions worth revising.'),
    'class-content-analysis': ('Audit course materials', 'Course content review', 'review', 'Specific gaps, overlap, and alignment findings.'),
    'exam-predictor': ('Plan pre-exam support', 'Exam readiness', 'review', 'Topic evidence and possible support actions.'),
    'prof-brain': ('Organize my materials', 'Prof brain', 'organize', 'An indexed course knowledge base without student records.'),
    'canvas-lms': ('Work in Canvas', 'Canvas operations', 'organize', 'A verified workflow for reviewed LMS changes.'),
}

def main():
    site = ROOT / 'web/dist'
    downloads = site / 'downloads'
    downloads.mkdir(parents=True, exist_ok=True)
    legacy = ROOT / 'dist'
    legacy.mkdir(exist_ok=True)
    catalog = []
    hashes = {}
    for skill in sorted(skills(), key=lambda p: list(LABELS).index(p.name)):
        raw = read_public_file(skill / 'SKILL.md').decode('utf-8')
        task, title, category, outcome = LABELS[skill.name]
        parts = sections(raw)
        entry = {'id': skill.name, 'task': task, 'title': title, 'category': category, 'outcome': outcome,
                 'description': json.loads(re.search(r'^description: (.+)$', raw, re.M)[1]),
                 'needs': next((body for heading, body in parts if heading == 'What you need'), 'One teaching task you want help with.'),
                 'checks': next((body for heading, body in parts if heading.startswith('What to check')), ''),
                 'guardrail': next(body for heading, body in parts if heading == 'The guardrail'),
                 'prompts': prompt_blocks(raw), 'markdown': raw}
        catalog.append(entry)
        files = portable_files(skill)
        entries = {skill.name + '/' + name: data for name, data in files.items()}
        archive = downloads / (skill.name + '.zip')
        archive_bytes(archive, entries)
        data = archive.read_bytes()
        (downloads / (skill.name + '.skill')).write_bytes(data)
        (legacy / (skill.name + '.skill')).write_bytes(data)
        (downloads / (skill.name + '.md')).write_text(raw)
        hashes[archive.name] = digest(data)
    docs = {}
    for path in [ROOT / name for name in ['INSTALL.md', 'GETTING-STARTED.md', 'FAQ.md', 'PRINCIPLES.md', 'CONTRIBUTING.md']] + sorted((ROOT / 'guides').glob('*.md')) + sorted((ROOT / 'docs').glob('*.md')):
        docs[path.relative_to(ROOT).as_posix()] = read_public_file(path).decode('utf-8')
    payload = {'skills': catalog, 'docs': docs, 'checked': '2026-09-10'}
    (site / 'catalog.js').write_text('/* Generated by scripts/build-toolkit.py. Do not edit. */\nwindow.TOOLKIT = ' + json.dumps(payload, ensure_ascii=False).replace('<', '\\u003c') + ';\n')
    (downloads / 'SHA256SUMS.txt').write_text(''.join(value + '  ' + name + '\n' for name, value in sorted(hashes.items())))
    # Full source bundle gives visual-only users everything needed for the local installer.
    source_entries = {}
    for folder in ['skills', 'guides', 'scripts', 'docs', 'tests']:
        for source in public_files(ROOT / folder):
            source_entries['ai-education/' + source.relative_to(ROOT).as_posix()] = read_public_file(source)
    for name in ['AGENTS.md', 'README.md', 'INSTALL.md', 'GETTING-STARTED.md', 'FAQ.md', 'GLOSSARY.md', 'CONTRIBUTING.md', 'PRINCIPLES.md', 'LICENSE']:
        source_entries['ai-education/' + name] = read_public_file(ROOT / name)
    for name in ['build-cookbook.js', 'package.json', 'package-lock.json', 'AI-Teaching-Cookbook.docx']:
        source_entries['ai-education/cookbook/' + name] = read_public_file(ROOT / 'cookbook' / name)
    source_entries['ai-education/LinkedIn-Article.md'] = read_public_file(ROOT / 'LinkedIn-Article.md')
    source_entries['ai-education/STATUS.md'] = b'# Release status\n\nSee docs/REVIEW.md for this release. Private workspace continuity is not distributed.\n'
    source_entries['ai-education/web/README.md'] = read_public_file(ROOT / 'web/README.md')
    for name in ['index.html', 'styles.css', 'app.js', 'catalog.js']:
        data = read_public_file(site / name)
        if name == 'index.html':
            # An archive cannot contain itself. Offline users already have the installer;
            # link the source copy to the repository for future downloads instead.
            data = data.replace(b'href="downloads/ai-teaching-toolkit-source.zip"', b'href="https://github.com/TaylorONeal/ai-education"')
        source_entries['ai-education/web/dist/' + name] = data
    # Include only outputs from this build, not arbitrary files left in downloads.
    download_names = ['SHA256SUMS.txt'] + [skill['id'] + extension for skill in catalog for extension in ['.zip', '.skill', '.md']]
    for name in download_names:
        source_entries['ai-education/web/dist/downloads/' + name] = read_public_file(downloads / name)
    archive_bytes(downloads / 'ai-teaching-toolkit-source.zip', source_entries)
    print('Built', len(catalog), 'skills, portable downloads, and the offline catalog.')

if __name__ == '__main__':
    main()
